// automatically generated by the FlatBuffers compiler, do not modify

package csbparser

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ColorVector struct {
	_tab flatbuffers.Struct
}

func (rcv *ColorVector) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ColorVector) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *ColorVector) VectorX() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *ColorVector) MutateVectorX(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *ColorVector) VectorY() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *ColorVector) MutateVectorY(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func CreateColorVector(builder *flatbuffers.Builder, vectorX float32, vectorY float32) flatbuffers.UOffsetT {
	builder.Prep(4, 8)
	builder.PrependFloat32(vectorY)
	builder.PrependFloat32(vectorX)
	return builder.Offset()
}
