// automatically generated by the FlatBuffers compiler, do not modify

package csbparser

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InnerActionFrame struct {
	_tab flatbuffers.Table
}

func GetRootAsInnerActionFrame(buf []byte, offset flatbuffers.UOffsetT) *InnerActionFrame {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InnerActionFrame{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *InnerActionFrame) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InnerActionFrame) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InnerActionFrame) FrameIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InnerActionFrame) MutateFrameIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *InnerActionFrame) Tween() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return true
}

func (rcv *InnerActionFrame) MutateTween(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *InnerActionFrame) InnerActionType() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InnerActionFrame) MutateInnerActionType(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *InnerActionFrame) CurrentAniamtionName() string {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.String(o + rcv._tab.Pos)
	}
	return ""
}

func (rcv *InnerActionFrame) SingleFrameIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InnerActionFrame) MutateSingleFrameIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func (rcv *InnerActionFrame) EasingData(obj *EasingData) *EasingData {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(EasingData)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func InnerActionFrameStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func InnerActionFrameAddFrameIndex(builder *flatbuffers.Builder, frameIndex int32) {
	builder.PrependInt32Slot(0, frameIndex, 0)
}
func InnerActionFrameAddTween(builder *flatbuffers.Builder, tween bool) {
	builder.PrependBoolSlot(1, tween, true)
}
func InnerActionFrameAddInnerActionType(builder *flatbuffers.Builder, innerActionType int32) {
	builder.PrependInt32Slot(2, innerActionType, 0)
}
func InnerActionFrameAddCurrentAniamtionName(builder *flatbuffers.Builder, currentAniamtionName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(currentAniamtionName), 0)
}
func InnerActionFrameAddSingleFrameIndex(builder *flatbuffers.Builder, singleFrameIndex int32) {
	builder.PrependInt32Slot(4, singleFrameIndex, 0)
}
func InnerActionFrameAddEasingData(builder *flatbuffers.Builder, easingData flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(easingData), 0)
}
func InnerActionFrameEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
