// automatically generated by the FlatBuffers compiler, do not modify

package csbparser

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PointFrame struct {
	_tab flatbuffers.Table
}

func GetRootAsPointFrame(buf []byte, offset flatbuffers.UOffsetT) *PointFrame {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PointFrame{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PointFrame) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PointFrame) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PointFrame) FrameIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PointFrame) MutateFrameIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *PointFrame) Tween() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return true
}

func (rcv *PointFrame) MutateTween(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *PointFrame) Position(obj *Position) *Position {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Position)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *PointFrame) EasingData(obj *EasingData) *EasingData {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(EasingData)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func PointFrameStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func PointFrameAddFrameIndex(builder *flatbuffers.Builder, frameIndex int32) {
	builder.PrependInt32Slot(0, frameIndex, 0)
}
func PointFrameAddTween(builder *flatbuffers.Builder, tween bool) {
	builder.PrependBoolSlot(1, tween, true)
}
func PointFrameAddPosition(builder *flatbuffers.Builder, position flatbuffers.UOffsetT) {
	builder.PrependStructSlot(2, flatbuffers.UOffsetT(position), 0)
}
func PointFrameAddEasingData(builder *flatbuffers.Builder, easingData flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(easingData), 0)
}
func PointFrameEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
