// automatically generated by the FlatBuffers compiler, do not modify

package csbparser

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RotationSkew struct {
	_tab flatbuffers.Struct
}

func (rcv *RotationSkew) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RotationSkew) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *RotationSkew) RotationSkewX() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *RotationSkew) MutateRotationSkewX(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *RotationSkew) RotationSkewY() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *RotationSkew) MutateRotationSkewY(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func CreateRotationSkew(builder *flatbuffers.Builder, rotationSkewX float32, rotationSkewY float32) flatbuffers.UOffsetT {
	builder.Prep(4, 8)
	builder.PrependFloat32(rotationSkewY)
	builder.PrependFloat32(rotationSkewX)
	return builder.Offset()
}
