// automatically generated by the FlatBuffers compiler, do not modify

package csbparser

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SingleNodeOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsSingleNodeOptions(buf []byte, offset flatbuffers.UOffsetT) *SingleNodeOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SingleNodeOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SingleNodeOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SingleNodeOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SingleNodeOptions) NodeOptions(obj *WidgetOptions) *WidgetOptions {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(WidgetOptions)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SingleNodeOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SingleNodeOptionsAddNodeOptions(builder *flatbuffers.Builder, nodeOptions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(nodeOptions), 0)
}
func SingleNodeOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
