// automatically generated by the FlatBuffers compiler, do not modify

package csbparser

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BlendFunc struct {
	_tab flatbuffers.Struct
}

func (rcv *BlendFunc) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BlendFunc) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *BlendFunc) Src() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *BlendFunc) MutateSrc(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *BlendFunc) Dst() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *BlendFunc) MutateDst(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func CreateBlendFunc(builder *flatbuffers.Builder, src int32, dst int32) flatbuffers.UOffsetT {
	builder.Prep(4, 8)
	builder.PrependInt32(dst)
	builder.PrependInt32(src)
	return builder.Offset()
}
