// automatically generated by the FlatBuffers compiler, do not modify

package csbparser

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FlatSize struct {
	_tab flatbuffers.Struct
}

func (rcv *FlatSize) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FlatSize) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *FlatSize) Width() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *FlatSize) MutateWidth(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *FlatSize) Height() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *FlatSize) MutateHeight(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func CreateFlatSize(builder *flatbuffers.Builder, width float32, height float32) flatbuffers.UOffsetT {
	builder.Prep(4, 8)
	builder.PrependFloat32(height)
	builder.PrependFloat32(width)
	return builder.Offset()
}
