// automatically generated by the FlatBuffers compiler, do not modify

package csbparser

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SpriteOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsSpriteOptions(buf []byte, offset flatbuffers.UOffsetT) *SpriteOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SpriteOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SpriteOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SpriteOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SpriteOptions) NodeOptions(obj *WidgetOptions) *WidgetOptions {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(WidgetOptions)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SpriteOptions) FileNameData(obj *ResourceData) *ResourceData {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ResourceData)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SpriteOptions) BlendFunc(obj *BlendFunc) *BlendFunc {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(BlendFunc)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SpriteOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func SpriteOptionsAddNodeOptions(builder *flatbuffers.Builder, nodeOptions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(nodeOptions), 0)
}
func SpriteOptionsAddFileNameData(builder *flatbuffers.Builder, fileNameData flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(fileNameData), 0)
}
func SpriteOptionsAddBlendFunc(builder *flatbuffers.Builder, blendFunc flatbuffers.UOffsetT) {
	builder.PrependStructSlot(2, flatbuffers.UOffsetT(blendFunc), 0)
}
func SpriteOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
